# Generated by Django 5.1.7 on 2025-05-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_postthread"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
