# Generated by Django 5.1.7 on 2025-05-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_is_anonymous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("news", "News"),
                    ("event", "Event"),
                    ("alert", "Alert"),
                    ("military", "Military"),
                    ("casualties", "Casualties"),
                    ("explosion", "Explosion"),
                    ("politics", "Politics"),
                    ("sports", "Sports"),
                    ("health", "Health"),
                    ("traffic", "Traffic"),
                    ("weather", "Weather"),
                    ("crime", "Crime"),
                    ("community", "Community"),
                    ("disaster", "Disaster"),
                    ("environment", "Environment"),
                    ("education", "Education"),
                    ("fire", "Fire"),
                    ("other", "Other"),
                ],
                default="news",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="category",
            field=models.CharField(
                choices=[
                    ("news", "News"),
                    ("event", "Event"),
                    ("alert", "Alert"),
                    ("military", "Military"),
                    ("casualties", "Casualties"),
                    ("explosion", "Explosion"),
                    ("politics", "Politics"),
                    ("sports", "Sports"),
                    ("health", "Health"),
                    ("traffic", "Traffic"),
                    ("weather", "Weather"),
                    ("crime", "Crime"),
                    ("community", "Community"),
                    ("disaster", "Disaster"),
                    ("environment", "Environment"),
                    ("education", "Education"),
                    ("fire", "Fire"),
                    ("other", "Other"),
                ],
                default="news",
                max_length=20,
            ),
        ),
    ]
