# Generated by Django 5.1.7 on 2025-05-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_category_alter_thread_category"),
    ]

    operations = [
        # Remove unused tables that were created by previous migrations
        # but are no longer defined in models.py
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS posts_postinteraction CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS posts_usercategoryinteraction CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS posts_userlocationpreference CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS posts_userrecommendationcache CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
    ]
