# Generated by Django 5.1.7 on 2025-05-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_remove_usercategorypreference"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostThread",
        ),
    ]
