# Generated by Django 5.1.7 on 2025-05-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_remove_postthread_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="thread",
        ),
        migrations.DeleteModel(
            name="Thread",
        ),
    ]
