# Generated by Django 5.1.7 on 2025-05-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_related_post"),
        ("posts", "0008_remove_thread_table"),
    ]

    operations = []
