# Generated by Django 5.1.7 on 2025-05-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_post_event_status_alter_post_status_eventstatusvote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="event_status",
        ),
    ]
