# Generated by Django 5.1.7 on 2025-05-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_update_status_to_event_status"),
        ("posts", "0011_remove_event_status_field"),
    ]

    operations = []
