# Generated by Django 5.1.7 on 2025-05-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_merge_20250526_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventstatusvote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="eventstatusvote",
            name="voted_ended",
            field=models.BooleanField(
                default=True, help_text="True if user thinks event ended"
            ),
        ),
    ]
