# Generated by Django 5.1.7 on 2025-06-08 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_alter_eventstatusvote_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("event", "Event"),
                            ("alert", "Alert"),
                            ("military", "Military"),
                            ("casualties", "Casualties"),
                            ("explosion", "Explosion"),
                            ("politics", "Politics"),
                            ("sports", "Sports"),
                            ("health", "Health"),
                            ("traffic", "Traffic"),
                            ("weather", "Weather"),
                            ("crime", "Crime"),
                            ("community", "Community"),
                            ("disaster", "Disaster"),
                            ("environment", "Environment"),
                            ("education", "Education"),
                            ("fire", "Fire"),
                            ("other", "Other"),
                        ],
                        help_text="Category that was interacted with",
                        max_length=20,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("filter", "Filter"),
                            ("view", "View"),
                            ("click", "Click"),
                        ],
                        default="filter",
                        help_text="Type of interaction with the category",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
