# Generated by Django 5.1.7 on 2025-06-08 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_create_category_interaction_with_counters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoryinteraction",
            options={"ordering": ["-last_updated"]},
        ),
        migrations.AddField(
            model_name="categoryinteraction",
            name="count",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of times this interaction has occurred"
            ),
        ),
        migrations.AddField(
            model_name="categoryinteraction",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="categoryinteraction",
            unique_together={("user", "category", "interaction_type")},
        ),
    ]
