# Generated by Django 5.1.7 on 2025-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0016_change_created_at_to_allow_custom_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
