# Generated by Django 5.1.7 on 2025-03-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_is_verified_alter_account_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
