# Generated by Django 5.1.7 on 2025-05-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_created_at_alter_account_last_login_and_more"),
        ("posts", "0004_alter_post_category_alter_thread_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="saved_posts",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by_profiles", to="posts.post"
            ),
        ),
    ]
