# Generated by Django 5.1.7 on 2025-05-31 12:23

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventconfirmation',
            name='unique_event_confirmation',
        ),
        migrations.RemoveConstraint(
            model_name='fcmtoken',
            name='unique_user_token',
        ),
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_friend_request',
        ),
        migrations.AlterField(
            model_name='eventconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='eventconfirmation',
            unique_together={('event_id', 'user', 'requested_at')},
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('user', 'token')},
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
