# Generated by Django 5.1.7 on 2025-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_remove_eventconfirmation_unique_event_confirmation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="follow_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notificationhistory",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("friend_request", "Friend Request"),
                    ("friend_request_accepted", "Friend Request Accepted"),
                    ("new_event", "New Event"),
                    ("still_there", "Still There Confirmation"),
                    ("event_update", "Event Update"),
                    ("event_cancelled", "Event Cancelled"),
                    ("nearby_event", "Nearby Event"),
                    ("reminder", "Reminder"),
                    ("system", "System Notification"),
                    ("new_follower", "New Follower"),
                    ("unfollowed", "Unfollowed"),
                ],
                max_length=50,
            ),
        ),
    ]
