# Generated by Django 5.1.7 on 2025-06-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationsettings_follow_notifications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmtoken",
            name="token",
            field=models.TextField(),
        ),
    ]
