# Generated by Django 5.1.7 on 2025-05-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
